# Default configuration for Vision Agent
app:
  name: "Universal Computer Vision Accessibility Agent"
  version: "0.1.0"
  debug: false

server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: false

database:
  url: "postgresql://user:password@localhost:5432/vision_agent"
  echo: false
  pool_size: 10
  max_overflow: 20

redis:
  url: "redis://localhost:6379/0"
  max_connections: 10
  cache_ttl: 3600  # 1 hour

llm_providers:
  openai:
    model: "gpt-4-vision-preview"
    max_tokens: 1000
    timeout: 30
  anthropic:
    model: "claude-3-5-sonnet-20241022"
    max_tokens: 1000
    timeout: 30
  google:
    model: "gemini-1.5-flash"
    max_tokens: 1000
    timeout: 30
  local:
    model: "llava-1.5-7b-hf"
    device: "cuda"
    max_tokens: 1000

accessibility:
  default_verbosity: "medium"
  tts_enabled: true
  tts_rate: 200
  tts_voice: "default"
  screen_reader_integration: true
  braille_output: false

processing:
  max_image_size: 2048
  jpeg_quality: 85
  cache_results: true
  batch_size: 4
  max_concurrent_requests: 10

security:
  encrypt_sensitive_data: true
  local_processing_for_pii: true
  max_request_size: "10MB"
  rate_limit_per_minute: 60

logging:
  level: "INFO"
  file: "logs/vision_agent.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_bytes: 10485760  # 10MB
  backup_count: 5